### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [bob-reus/karl-gjellerup_the-pilgrim-kamanita_john-f-logie#1]
### epigraph.xhtml:

- [x] Don Juan needs to be tagged as `<i epub:type="se:name.publication.poem">`

### chapter-10.xhtml:

- [x] Replace `<span class="sutra-quote">` with `<b>`.

- [x] Remove `class="sutra-quote` from the blockquotes. We avoid using classes that are only used once or twice. You can style the text with `<b>` instead.

### chapter-27.xhtml:

- [x] `Saccakiriya` needs italics and a language tag.

### note.xhtml:

- [x] This file name and id needs to be named afterword ([SEMOS 2.2.4.5](https://standardebooks.org/manual/1.7.0/single-page#2.2.4.5)). You will need to rerun `se build-manifest .`, `se build-spine .`, and `se build-toc .` after these changes.

**Comment by bob-reus** [comment]
All done!

I removed the custom css class, but did add the following to keep those blockquotes centered, as in the original:

`#chapter-10 blockquote:nth-of-type(3),
#chapter-10 blockquote:nth-of-type(4){
	text-align: center;
}`

If that is acceptable, this issue can be closed.

**Comment by EmmaSweeney** [comment]
The changes look good! I'll let Alex know this is ready for release.
